-- MySQL Script generated by MySQL Workbench
-- 10/20/16 14:00:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbEmpresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbEmpresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbEmpresa` DEFAULT CHARACTER SET utf8 ;
USE `dbEmpresa` ;

-- -----------------------------------------------------
-- Table `dbEmpresa`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEmpresa`.`clientes` (
  `idCliente` INT(11) NOT NULL,
  `nombres` VARCHAR(60) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `NIT` VARCHAR(12) NOT NULL,
  `genero` BIT(1) NOT NULL,
  `telefono` VARCHAR(25) NOT NULL,
  `correo_electronico` VARCHAR(45) NOT NULL,
  `fechaingreso` DATETIME NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbEmpresa`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEmpresa`.`marcas` (
  `idmarca` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbEmpresa`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEmpresa`.`productos` (
  `idProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(50) NOT NULL,
  `idmarca` SMALLINT(6) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Imagen` VARCHAR(30) NOT NULL,
  `precio_costo` DECIMAL(8,2) NOT NULL,
  `precio_venta` DECIMAL(8,2) NOT NULL,
  `existencia` INT(11) NOT NULL,
  `fecha_ingreso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `idmarca_idx` (`idmarca` ASC),
  CONSTRAINT `idmarca`
    FOREIGN KEY (`idmarca`)
    REFERENCES `dbEmpresa`.`marcas` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbEmpresa`.`puestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEmpresa`.`puestos` (
  `idPuesto` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `puesto` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPuesto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbEmpresa`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEmpresa`.`empleados` (
  `idEmpleado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(60) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `direccion` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(25) NOT NULL,
  `DPI` VARCHAR(15) NOT NULL,
  `genero` BIT(1) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `idPuesto` SMALLINT(6) NOT NULL,
  `fecha_inicio_labores` DATE NOT NULL,
  `fechaingreso` DATETIME NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `idPuesto_idx` (`idPuesto` ASC),
  CONSTRAINT `idPuesto`
    FOREIGN KEY (`idPuesto`)
    REFERENCES `dbEmpresa`.`puestos` (`idPuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbEmpresa`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEmpresa`.`ventas` (
  `idVenta` INT(11) NOT NULL AUTO_INCREMENT,
  `nofactura` INT(11) NOT NULL,
  `serie` CHAR(1) NOT NULL,
  `fechafactura` DATE NOT NULL,
  `idCliente` INT(11) NOT NULL,
  `idEmpleado` INT(11) NOT NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `idCliente_idx` (`idCliente` ASC),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `dbEmpresa`.`clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `dbEmpresa`.`empleados` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbEmpresa`.`ventas_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEmpresa`.`ventas_detalle` (
  `idventa_detalle` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `idVenta` INT(11) NOT NULL,
  `idProducto` INT(11) NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `precio_unitario` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`idventa_detalle`),
  INDEX `idProducto2_idx` (`idProducto` ASC),
  INDEX `idVenta_idx` (`idVenta` ASC),
  CONSTRAINT `idProducto2`
    FOREIGN KEY (`idProducto`)
    REFERENCES `dbEmpresa`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idVenta`
    FOREIGN KEY (`idVenta`)
    REFERENCES `dbEmpresa`.`ventas` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbEmpresa`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEmpresa`.`proveedores` (
  `idProveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `proveedor` VARCHAR(60) NOT NULL,
  `NIT` VARCHAR(12) NOT NULL,
  `direccion` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbEmpresa`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEmpresa`.`compras` (
  `idcompra` INT(11) NOT NULL AUTO_INCREMENT,
  `no_orden_compra` INT(11) NOT NULL,
  `idProveedor` INT(11) NOT NULL,
  `fecha_orden` DATE NOT NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `idProveedor_idx` (`idProveedor` ASC),
  CONSTRAINT `idProveedor`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `dbEmpresa`.`proveedores` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbEmpresa`.`compras_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEmpresa`.`compras_detalle` (
  `idcompra_detalle` BIGINT(20) NOT NULL,
  `idcompra` INT(11) NOT NULL,
  `idProducto` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `precio_costo_unitario` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`idcompra_detalle`),
  INDEX `idProductos_idx` (`idProducto` ASC),
  INDEX `idCompra_idx` (`idcompra` ASC),
  CONSTRAINT `idCompra`
    FOREIGN KEY (`idcompra`)
    REFERENCES `dbEmpresa`.`compras` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProductos`
    FOREIGN KEY (`idProducto`)
    REFERENCES `dbEmpresa`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
